Repository Wolfgang-Solutions/Teaching, pull requests merged in 2020-07, with the labels that each got.

#1 Create node.js.yml
  .github/workflows/node.js.yml
Labels: documentation

#2 Create stale.yml
  .github/workflows/stale.yml
Labels: good first issue

#3 Added CLI
  angular.json
Labels: enhancement, good first issue

#7 Dharmin
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/download/download.component.html
  src/app/download/download.component.scss
  src/app/download/download.component.spec.ts
  src/app/download/download.component.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.scss
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/main/main.component.html
  src/app/main/main.component.scss
  src/app/main/main.component.spec.ts
  src/app/main/main.component.ts
  src/app/pricing/pricing.component.html
  src/app/pricing/pricing.component.scss
  src/app/pricing/pricing.component.spec.ts
  src/app/pricing/pricing.component.ts
  src/assets/wolfgang.jpg
  src/index.html
  src/styles.scss
Labels: enhancement, good first issue
